package hashcat

import (
	"strconv"
)

type hashAlgorithm struct {
	Group  string
	Name   string
	Number string
}

type hashAlgorithms []hashAlgorithm

func (h hashAlgorithms) Len() int {
	return len(h)

}
func (h hashAlgorithms) Swap(i, j int) {
	h[i], h[j] = h[j], h[i]
}

func (h hashAlgorithms) Less(i, j int) bool {
	iNum, _ := strconv.Atoi(h[i].Number)
	jNum, _ := strconv.Atoi(h[j].Number)
	return iNum < jNum
}

var algorithms = []hashAlgorithm{
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "MD4", Number: "900"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "MD5", Number: "0"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "Half MD5", Number: "5100"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "SHA1", Number: "100"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "SHA-384", Number: "10800"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "SHA-256", Number: "1400"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "SHA-512", Number: "1700"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "SHA-3 (Keccak)", Number: "5000"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "SipHash", Number: "10100"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "RipeMD160", Number: "6000"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "Whirlpool", Number: "6100"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "GOST R 34.11-94", Number: "6900"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "GOST R 34.11-2012 (Streebog) 256-bit", Number: "11700"},
	hashAlgorithm{Group: "Roll-your-own: Raw Hashes", Name: "GOST R 34.11-2012 (Streebog) 512-bit", Number: "11800"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5($pass.$salt)", Number: "10"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5($salt.$pass)", Number: "20"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5(unicode($pass).$salt)", Number: "30"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5($salt.unicode($pass))", Number: "40"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5($salt.$pass.$salt)", Number: "3800"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5($salt.md5($pass))", Number: "3710"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5(md5($pass)", Number: "2600"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5(strtoupper(md5($pass)))", Number: "4300"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "md5(sha1($pass))", Number: "4400"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1($pass.$salt)", Number: "110"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1($salt.$pass)", Number: "120"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1(unicode($pass).$salt)", Number: "130"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1($salt.unicode($pass))", Number: "140"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1(sha1($pass)", Number: "4500"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1(md5($pass))", Number: "4700"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha1($salt.$pass.$salt)", Number: "4900"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha256($pass.$salt)", Number: "1410"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha256($salt.$pass)", Number: "1420"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha256(unicode($pass).$salt)", Number: "1430"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha256($salt.unicode($pass))", Number: "1440"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha512($pass.$salt)", Number: "1710"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha512($salt.$pass)", Number: "1720"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha512(unicode($pass).$salt)", Number: "1730"},
	hashAlgorithm{Group: "Roll-your-own: Iterated and / or Salted Hashes", Name: "sha512($salt.unicode($pass))", Number: "1740"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-MD5 (key = $pass)", Number: "50"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-MD5 (key = $salt)", Number: "60"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-SHA1 (key = $pass)", Number: "150"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-SHA1 (key = $salt)", Number: "160"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-SHA256 (key = $pass)", Number: "1450"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-SHA256 (key = $salt)", Number: "1460"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-SHA512 (key = $pass)", Number: "1750"},
	hashAlgorithm{Group: "Roll-your-own: Authenticated Hashes", Name: "HMAC-SHA512 (key = $salt)", Number: "1760"},
	hashAlgorithm{Group: "Generic KDF", Name: "phpass", Number: "400"},
	hashAlgorithm{Group: "Generic KDF", Name: "scrypt", Number: "8900"},
	hashAlgorithm{Group: "Generic KDF", Name: "PBKDF2-HMAC-MD5", Number: "11900"},
	hashAlgorithm{Group: "Generic KDF", Name: "PBKDF2-HMAC-SHA1", Number: "12000"},
	hashAlgorithm{Group: "Generic KDF", Name: "PBKDF2-HMAC-SHA256", Number: "10900"},
	hashAlgorithm{Group: "Generic KDF", Name: "PBKDF2-HMAC-SHA512", Number: "12100"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "Skype", Number: "23"},
	//hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "WPA/WPA2", Number: "2500"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "iSCSI CHAP authentication, MD5(Chap)", Number: "4800"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "IKE-PSK MD5", Number: "5300"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "IKE-PSK SHA1", Number: "5400"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "NetNTLMv1", Number: "5500"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "NetNTLMv1 + ESS", Number: "5500"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "NetNTLMv2", Number: "5600"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "IPMI2 RAKP HMAC-SHA1", Number: "7300"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "Kerberos 5 AS-REQ Pre-Auth etype 23", Number: "7500"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "DNSSEC (NSEC3)", Number: "8300"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "Cram MD5", Number: "10200"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "PostgreSQL Challenge-Response Authentication (MD5)", Number: "11100"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "MySQL Challenge-Response Authentication (SHA1)", Number: "11200"},
	hashAlgorithm{Group: "Network protocols, Challenge-Response", Name: "SIP digest authentication (MD5)", Number: "11400"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "SMF (Simple Machines Forum)", Number: "121"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "phpBB3", Number: "400"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "vBulletin < v3.8.5", Number: "2611"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "vBulletin > v3.8.5", Number: "2711"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "MyBB", Number: "2811"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "IPB (Invison Power Board)", Number: "2811"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "WBB3 (Woltlab Burning Board)", Number: "8400"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Joomla < 2.5.18", Number: "11"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Joomla > 2.5.18", Number: "400"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Wordpress", Number: "400"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "PHPS", Number: "2612"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Drupal7", Number: "7900"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "osCommerce", Number: "21"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "xt:Commerce", Number: "21"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "PrestaShop", Number: "11000"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Django (SHA-1)", Number: "124"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Django (PBKDF2-SHA256)", Number: "10000"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Mediawiki B type", Number: "3711"},
	hashAlgorithm{Group: "Forums, CMS, E-Commerce, Frameworks, Middleware, Wiki, Management", Name: "Redmine", Number: "7600"},
	hashAlgorithm{Group: "Database Server", Name: "PostgreSQL", Number: "12"},
	hashAlgorithm{Group: "Database Server", Name: "MSSQL(2000)", Number: "131"},
	hashAlgorithm{Group: "Database Server", Name: "MSSQL(2005)", Number: "132"},
	hashAlgorithm{Group: "Database Server", Name: "MSSQL(2012)", Number: "1731"},
	hashAlgorithm{Group: "Database Server", Name: "MSSQL(2014)", Number: "1731"},
	hashAlgorithm{Group: "Database Server", Name: "MySQL323", Number: "200"},
	hashAlgorithm{Group: "Database Server", Name: "MySQL4.1/MySQL5", Number: "300"},
	hashAlgorithm{Group: "Database Server", Name: "Oracle H: Type (Oracle 7+)", Number: "3100"},
	hashAlgorithm{Group: "Database Server", Name: "Oracle S: Type (Oracle 11+)", Number: "112"},
	hashAlgorithm{Group: "Database Server", Name: "Oracle T: Type (Oracle 12+)", Number: "12300"},
	hashAlgorithm{Group: "Database Server", Name: "Sybase ASE", Number: "8000"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "EPiServer 6.x < v4", Number: "141"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "EPiServer 6.x > v4", Number: "1441"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "Apache $apr1$", Number: "1600"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "ColdFusion 10+", Number: "12600"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "hMailServer", Number: "1421"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "nsldap, SHA-1(Base64), Netscape LDAP SHA", Number: "101"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "nsldaps, SSHA-1(Base64), Netscape LDAP SSHA", Number: "111"},
	hashAlgorithm{Group: "HTTP, SMTP, LDAP Server", Name: "SSHA-512(Base64), LDAP {SSHA512}", Number: "1711"},
	hashAlgorithm{Group: "Checksums", Name: "CRC32", Number: "11500"},
	hashAlgorithm{Group: "Operating-Systems", Name: "LM", Number: "3000"},
	hashAlgorithm{Group: "Operating-Systems", Name: "NTLM", Number: "1000"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Domain Cached Credentials (DCC), MS Cache", Number: "1100"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Domain Cached Credentials 2 (DCC2), MS Cache 2", Number: "2100"},
	hashAlgorithm{Group: "Operating-Systems", Name: "MS-AzureSync PBKDF2-HMAC-SHA256", Number: "12800"},
	hashAlgorithm{Group: "Operating-Systems", Name: "descrypt, DES(Unix), Traditional DES", Number: "1500"},
	hashAlgorithm{Group: "Operating-Systems", Name: "BSDiCrypt, Extended DES", Number: "12400"},
	hashAlgorithm{Group: "Operating-Systems", Name: "md5crypt $1$, MD5(Unix)", Number: "500"},
	hashAlgorithm{Group: "Operating-Systems", Name: "bcrypt $2*$, Blowfish(Unix)", Number: "3200"},
	hashAlgorithm{Group: "Operating-Systems", Name: "sha256crypt $5$, SHA256(Unix)", Number: "7400"},
	hashAlgorithm{Group: "Operating-Systems", Name: "sha512crypt $6$, SHA512(Unix)", Number: "1800"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.4", Number: "122"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.5", Number: "122"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.6", Number: "122"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.7", Number: "1722"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.8", Number: "7100"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.9", Number: "7100"},
	hashAlgorithm{Group: "Operating-Systems", Name: "OSX v10.10", Number: "7100"},
	hashAlgorithm{Group: "Operating-Systems", Name: "AIX {smd5}", Number: "6300"},
	hashAlgorithm{Group: "Operating-Systems", Name: "AIX {ssha1}", Number: "6700"},
	hashAlgorithm{Group: "Operating-Systems", Name: "AIX {ssha256}", Number: "6400"},
	hashAlgorithm{Group: "Operating-Systems", Name: "AIX {ssha512}", Number: "6500"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Cisco-PIX", Number: "2400"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Cisco-ASA", Number: "2410"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Cisco-IOS $1$", Number: "500"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Cisco-IOS $4$", Number: "5700"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Cisco-IOS $8$", Number: "9200"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Cisco-IOS $9$", Number: "9300"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Juniper Netscreen/SSG (ScreenOS)", Number: "22"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Juniper IVE", Number: "501"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Android PIN", Number: "5800"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Citrix Netscaler", Number: "8100"},
	hashAlgorithm{Group: "Operating-Systems", Name: "RACF", Number: "8500"},
	hashAlgorithm{Group: "Operating-Systems", Name: "GRUB 2", Number: "7200"},
	hashAlgorithm{Group: "Operating-Systems", Name: "Radmin2", Number: "9900"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "SAP CODVN B (BCODE)", Number: "7700"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "SAP CODVN F/G (PASSCODE)", Number: "7800"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "SAP CODVN H (PWDSALTEDHASH) iSSHA-1", Number: "10300"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "Lotus Notes/Domino 5", Number: "8600"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "Lotus Notes/Domino 6", Number: "8700"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "Lotus Notes/Domino 8", Number: "9100"},
	hashAlgorithm{Group: "Enterprise Application Software EAS", Name: "PeopleSoft", Number: "133"},
	// hashAlgorithm{Group: "Archives", Name: "7-Zip", Number: "11600"},
	// hashAlgorithm{Group: "Archives", Name: "RAR3-hp", Number: "12500"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-RipeMD160 XTS  512 bit (Ciphers: AES or Serpent or Twofish)", Number: "6211"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-RipeMD160 XTS 1024 bit (Ciphers: AES or Serpent or Twofish or AES-Twofish or Serpent-AES or Twofish-Serpent)", Number: "6212"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-RipeMD160 XTS 1536 bit (Ciphers: All)", Number: "6213"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-SHA512 XTS  512 bit (Ciphers: AES or Serpent or Twofish)", Number: "6221"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-SHA512 XTS 1024 bit (Ciphers: AES or Serpent or Twofish or AES-Twofish or Serpent-AES or Twofish-Serpent)", Number: "6222"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-SHA512 XTS 1536 bit (Ciphers: All)", Number: "6223"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-Whirlpool XTS  512 bit (Ciphers: AES or Serpent or Twofish) (TrueCrypt 5.0+)", Number: "6231"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-Whirlpool XTS 1024 bit (Ciphers: AES or Serpent or Twofish or AES-Twofish or Serpent-AES or Twofish-Serpent)", Number: "6232"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-Whirlpool XTS 1536 bit (Ciphers: All)", Number: "6233"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-RipeMD160 + boot-mode XTS  512 bit (Ciphers: AES or Serpent or Twofish) (TrueCrypt 5.0+)", Number: "6241"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-RipeMD160 + boot-mode XTS 1024 bit (Ciphers: AES or Serpent or Twofish or AES-Twofish or Serpent-AES or Twofish-Serpent)", Number: "6242"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "TrueCrypt 5.0+ PBKDF2-HMAC-RipeMD160 + boot-mode XTS 1536 bit (Ciphers: All)", Number: "6243"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "Android FDE < v4.3", Number: "8800"},
	// hashAlgorithm{Group: "Full-Disk encryptions FDE", Name: "eCryptfs", Number: "12200"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office <= 2003 MD5 + RC4, oldoffice$0, oldoffice$1", Number: "9700"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office <= 2003 MD5 + RC4, collider-mode #1", Number: "9710"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office <= 2003 MD5 + RC4, collider-mode #2", Number: "9720"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office <= 2003 SHA1 + RC4, oldoffice$3, oldoffice$4", Number: "9800"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office <= 2003 SHA1 + RC4, collider-mode #1", Number: "9810"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office <= 2003 SHA1 + RC4, collider-mode #2", Number: "9820"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office 2007", Number: "9400"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office 2010", Number: "9500"},
	// hashAlgorithm{Group: "Documents", Name: "MS Office 2013", Number: "9600"},
	// hashAlgorithm{Group: "Documents", Name: "PDF 1.1 - 1.3 (Acrobat 2 - 4)", Number: "10400"},
	// hashAlgorithm{Group: "Documents", Name: "PDF 1.1 - 1.3 (Acrobat 2 - 4) + collider-mode #1", Number: "10410"},
	// hashAlgorithm{Group: "Documents", Name: "PDF 1.1 - 1.3 (Acrobat 2 - 4) + collider-mode #2", Number: "10420"},
	// hashAlgorithm{Group: "Documents", Name: "PDF 1.4 - 1.6 (Acrobat 5 - 8)", Number: "10500"},
	// hashAlgorithm{Group: "Documents", Name: "PDF 1.7 Level 3 (Acrobat 9)", Number: "10600"},
	// hashAlgorithm{Group: "Documents", Name: "PDF 1.7 Level 8 (Acrobat 10 - 11)", Number: "10700"},
	// hashAlgorithm{Group: "Password Managers", Name: "Password Safe v2", Number: "9000"},
	// hashAlgorithm{Group: "Password Managers", Name: "Password Safe v3", Number: "5200"},
	// hashAlgorithm{Group: "Password Managers", Name: "Lastpass", Number: "6800"},
	// hashAlgorithm{Group: "Password Managers", Name: "1Password, agilekeychain", Number: "6600"},
	// hashAlgorithm{Group: "Password Managers", Name: "1Password, cloudkeychain", Number: "8200"},
	// hashAlgorithm{Group: "Password Managers", Name: "Bitcoin/Litecoin wallet.dat", Number: "11300"},
	// hashAlgorithm{Group: "Password Managers", Name: "Blockchain, My Wallet", Number: "12700"},
}
